# Generated by Django 5.2 on 2025-05-06 20:00

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=123, null=True)),
                ("status", models.BooleanField(default=True)),
                ("discount", models.CharField(blank=True, max_length=123, null=True)),
                ("price", models.CharField(blank=True, max_length=123, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("oblasti", models.CharField(max_length=255)),
                ("days", models.CharField(max_length=255)),
                ("nights", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=255)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                            ("Extreme", "Extreme"),
                        ],
                        max_length=123,
                    ),
                ),
                ("max_height", models.CharField(blank=True, max_length=123, null=True)),
                ("type", models.CharField(blank=True, max_length=123, null=True)),
                ("trip_days", models.CharField(blank=True, max_length=123, null=True)),
                ("start", models.CharField(blank=True, max_length=123, null=True)),
                ("mini_title", models.CharField(blank=True, max_length=123, null=True)),
                ("description", ckeditor.fields.RichTextField()),
                ("code", models.CharField(blank=True, max_length=123, null=True)),
                (
                    "accomodation",
                    models.CharField(blank=True, max_length=123, null=True),
                ),
                (
                    "transportation",
                    models.CharField(blank=True, max_length=123, null=True),
                ),
                ("image", models.FileField(upload_to="destinations/")),
                ("map", models.FileField(blank=True, null=True, upload_to="maps/")),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Features",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=123)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=123, null=True)),
                ("reiting", models.CharField(blank=True, max_length=1, null=True)),
                ("image", models.ImageField(upload_to="avatars/")),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImageGalleryDestination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="gallery/")),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField()),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="images",
                        to="main.destination",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Itenary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=123, null=True)),
                ("day", models.CharField(blank=True, max_length=123, null=True)),
                ("icon", models.CharField(blank=True, max_length=123, null=True)),
                ("created_at", models.DateTimeField()),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="iternaries",
                        to="main.destination",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
