# Generated by Django 5.2 on 2025-05-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="features",
            field=models.ManyToManyField(to="main.features"),
        ),
    ]
