# Generated by Django 5.2 on 2025-05-06 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_destination_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="dateprice",
            name="destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prices",
                to="main.destination",
            ),
        ),
    ]
