# Generated by Django 5.2 on 2025-05-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_dateprice_destination"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=123)),
                ("description", models.TextField()),
                ("icon", models.CharField(max_length=123)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
