# Generated by Django 5.2 on 2025-05-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_category_tag_news"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="image",
            field=models.FileField(default=1, upload_to="images/"),
            preserve_default=False,
        ),
    ]
