# Generated by Django 5.2 on 2025-05-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_sitesetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="country",
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
    ]
