# Generated by Django 5.2 on 2025-05-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_review_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="image_review",
            field=models.FileField(default=1, upload_to="images"),
            preserve_default=False,
        ),
    ]
