# Generated by Django 5.2 on 2025-05-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_sitesetting_image_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
