# Generated by Django 5.2 on 2025-05-15 10:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_faq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
