# Generated by Django 5.2 on 2025-05-22 11:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_newslettersubscriber"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="description_de",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="description_en",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="mini_description_de",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="mini_description_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_de",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
