# Generated by Django 5.2 on 2025-05-22 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_answeroption_text_de_answeroption_text_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="main.destination",
            ),
        ),
    ]
