# Generated by Django 5.2 on 2025-05-27 11:00

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_review_destination"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaqCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("title_de", models.CharField(max_length=255, null=True)),
                ("description", ckeditor.fields.RichTextField()),
                ("description_en", ckeditor.fields.RichTextField(null=True)),
                ("description_de", ckeditor.fields.RichTextField(null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Категория для Faq",
                "verbose_name_plural": "Категории для Faq",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="faq",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faqs",
                to="main.faqcategory",
            ),
        ),
    ]
