# Generated by Django 5.2 on 2025-06-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_alter_faqcategory_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="image_contact",
            field=models.FileField(blank=True, null=True, upload_to="images"),
        ),
    ]
