# Generated by Django 5.2 on 2025-06-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_sitesetting_image_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="slug",
            field=models.SlugField(blank=True, null=True, verbose_name="Слаг"),
        ),
        migrations.AddField(
            model_name="news",
            name="slug",
            field=models.SlugField(blank=True, unique=True, verbose_name="Слаг"),
        ),
    ]
