# Generated by Django 5.2 on 2025-07-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_destination_slug_news_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="map_iframe",
            field=models.TextField(blank=True, null=True),
        ),
    ]
