# Generated by Django 5.2 on 2025-06-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_destination_slug_news_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination",
            name="slug",
            field=models.SlugField(blank=True, null=True, verbose_name="Слаг"),
        ),
    ]
